CFLAGS = -g -Wall -std=c11

find_a_word: find_a_word.o

valid_pan_format: valid_pan_format.o

hackerrank_tweets: hackerrank_tweets.o

find_hackerrank: find_hackerrank.o

detect_html_tags: detect_html_tags.o

detecting_valid_latitude_and_longitude: detecting_valid_latitude_and_longitude.o

stack_exchange_scraper: stack_exchange_scraper.o

clean:
	@rm -f *.o
